### PR TITLE
Update whitespace and string formatting

### PR DESCRIPTION
**Pull request by ghost**
Author: Victor Scott Cushman <VictorSCushman@gmail.com>

### CODE REVIEW

**Comment by ghost** [comment]
This PR also fixes what *may* be a bug.

In the [harvester](https://github.com/tachyo/SMMData/blob/0357dbfa5b2ebdc711fcd937eeecaed99cfcca3c/SMMHarvester.py#L38) it looks like exponentiation was being used instead of multiplication. Not sure if this is a bug or if it was intended and the `print` string was wrong, but this PR changed it to match the string in the `print` statement.

**Comment by sugar700** [comment]
Interestingly, the `tries` thing seems like a bug, but for a different reason, the `tries` variable will always be `0`, as it's never updated. This means it will always sleep 0 seconds.

**Comment by ghost** [comment]
@xfix I went ahead and fixed that in [here](https://github.com/tachyo/SMMData/pull/2/commits/d65ab900485a8deab887dd7a2d493e1d9decf4ce).

**Comment by tachyo** [comment]
Thank you :)
looks like we are on a good way to make this actual, production ready, code ;P

Now that the `tries` are incremented correctly we should consider a non-linear wait time between them. i will create a pull request for that shortly. Than we can discuss a a few ideas

**Pull request merged**
